module.exports = {
  MONGO_URI: process.env.MONGO_URI,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_SECRET_KEY_ID: process.env.AWS_SECRET_KEY_ID,
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
};
